#ifndef BUCKET_HEAP_CONFIG_H
#define BUCKET_HEAP_CONFIG_H

#ifndef BUCKET_HEAP_CONFIG_PAGE_ALLOC_SIZE_KB
#define BUCKET_HEAP_CONFIG_PAGE_ALLOC_SIZE_KB 64
#endif

#ifndef BUCKET_HEAP_CONFIG_MIN_OBJECT_SIZE
#define BUCKET_HEAP_CONFIG_MIN_OBJECT_SIZE 8
#endif

#ifndef BUCKET_HEAP_CONFIG_MAX_OBJECT_SIZE
#define BUCKET_HEAP_CONFIG_MAX_OBJECT_SIZE 2048
#endif

#endif